# Generated by Django 3.0 on 2019-12-10 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
